# words.py

# These are all the words that are used to create the phrases used for verification

ADJECTIVES = ["abrupt", "acidic", "adorable", "adventurous", "aggressive", "agitated", "alert", "aloof", "bored", "brave", "bright", "colossal", "condescending", "confused", "cooperative", "corny", "costly", "courageous", "cruel", "despicable", "determined", "dilapidated", "diminutive", "distressed", "disturbed", "dizzy", "exasperated", "excited", "exhilarated", "extensive", "exuberant", "frothy", "frustrating", "funny", "fuzzy", "gaudy", "graceful", "greasy", "grieving", "gritty", "grotesque", "grubby", "grumpy", "handsome", "happy", "hollow", "hungry", "hurt", "icy", "ideal", "immense", "impressionable", "intrigued", "irate", "foolish", "frantic", "fresh", "friendly", "frightened", "frothy", "frustrating", "glorious", "gorgeous", "grubby", "happy", "harebrained", "healthy", "helpful", "helpless", "high", "hollow", "homely", "large", "lazy", "livid", "lonely", "loose", "lovely", "lucky", "mysterious", "narrow", "nasty", "outrageous", "panicky", "perfect", "perplexed", "quizzical", "teeny", "tender", "tense", "terrible", "tricky", "troubled", "unsightly", "upset", "wicked", "yummy", "zany", "zealous", "zippy"]
NAMES = ["Michael", "Christopher", "Jessica", "Matthew", "Ashley", "Jennifer", "Joshua", "Amanda", "Daniel", "David", "James", "Robert", "John", "Joseph", "Andrew", "Ryan", "Brandon", "Jason", "Justin", "Sarah", "William", "Jonathan", "Stephanie", "Brian", "Nicole", "Nicholas", "Anthony", "Heather", "Eric", "Elizabeth", "Adam", "Megan", "Melissa", "Kevin", "Steven", "Thomas", "Timothy", "Christina", "Kyle", "Rachel", "Laura", "Lauren", "Amber", "Brittany", "Danielle", "Richard", "Kimberly", "Jeffrey", "Amy",
         "Crystal", "Michelle", "Tiffany", "Jeremy", "Benjamin", "Mark", "Emily", "Aaron", "Charles", "Rebecca", "Jacob", "Stephen", "Patrick", "Sean", "Erin", "Zachary", "Jamie", "Kelly", "Samantha", "Nathan", "Sara", "Dustin", "Paul", "Angela", "Tyler", "Scott", "Katherine", "Andrea", "Gregory", "Erica", "Mary", "Travis", "Lisa", "Kenneth", "Bryan", "Lindsey", "Kristen", "Jose", "Alexander", "Jesse", "Katie", "Lindsay", "Shannon", "Vanessa", "Courtney", "Christine", "Alicia", "Cody", "Allison", "Bradley", "Samuel"]
ACTIONS = ["accepted", "adopted", "baked", "borrowed", "called", "chased", "collected", "delivered", "helped", "introduced", "kicked", "liked", "needed", "painted", "printed", "remembered", "returned", "saved", "brushed", "challenged", "cheated on", "clapped", "copied", "destroyed", "enjoyed", "gathered", "hoped", "joked with",
           "kissed", "listened to", "offered", "sacrificed", "insulted", "parked beside", "studied with", "stopped", "thanked", "walked to", "walked with", "argued with", "appreciated", "attacked", "buried", "cleaned", "divided", "identified", "laughed at", "moved", "opened", "played with", "pushed", "used", "visited", "waited for", "yelled at"]
TIMES = ["last week", "yesterday", "a month ago", "last year", "today", "an hour ago", "at 10am", "this morning", "this afternoon", "at lunch time", "at dinner time", "a while ago", "every day", "every day until the incident",
         "always, until that fateful day", "sometimes", "rarely", "often", "frequently", "disturbingly often", "so often that it frankly makes me sick", "twice a day", "once in a blue moon", "as often as felt necessary"]